### ISSUE TITLE
Big TODO list

### ISSUE THREAD

**Issue by Landerson352** [Landerson352/frontend-scaffold#2]
- [x] Commit Bootstrap 4 SCSS files.
- [x] Remove Grid system, Jumbotron, Carousel, Navbar (there are better alternatives).
- [x] Convert Bootstrap from SCSS to LESS.
- [x] Simplify Bootstrap (remove `@enable-xxx` variables, convert array maps to imperative calls, kill gratuitous abstractions, combine variable/mixin/component files.
- [x] Reorganize LESS folder structure into `components` and `utilities` only.
- [x] Make `@spacer` system more sane with multiplied `@unit`.
- [x] Implement BEM-lite in Bootstrap components (eg: `.btn`, `.btn.is-green.is-outline`).
- [x] Implement [Tympanus off-canvas nav](https://tympanus.net/Development/SidebarTransitions/) scaffolding.
- [x] Implement Feigelis-style type ramp.
- [x] Implement [opt-in typography](https://css-tricks.com/opt-in-typography/) container with Wordpress image alignment support.
- [x] Install React router for simple page navigation.
- [ ] Extend BS4 form styles onto gravity forms markup. **(In progress)**
- [ ] Add [Slick](http://kenwheeler.github.io/slick/) touch-friendly, React-friendly carousel. **(In progress)**
- [ ] Add easy way to enable fixed header.
- [ ] Fine-tune breakpoints. (The original ones are based on the BS4 grid.)
